#
#   Thiscovery API - THIS Institute’s citizen science platform
#   Copyright (C) 2019 THIS Institute
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   A copy of the GNU Affero General Public License is available in the
#   docs folder of this project.  It is also available www.gnu.org/licenses/
#
import os
from thiscovery_dev_tools.test_data.surveys_test_data import TEST_USER_INTERVIEW_TASK


td = {
    "test_appointment_id": 399682887,
    "dev_appointment_id": 448161724,
    "dev_appointment_no_link_id": 451427483,
    "dev_appointment_no_link_participant_not_in_thiscovery_database_id": 610938744,
    "dev_appointment_no_link_participant_does_not_have_user_project": 451904182,
    "test_appointment_no_notif_id": 448161419,
    "past_test_appointment_id": 437321459,
    "test_appointment_type_id": 14792299,
    "dev_appointment_type_id": 14649911,
    "test_appointment_no_notif_type_id": 17268193,
    "dev_appointment_no_link_type_id": 17271544,
    "calendar_id": 4038206,
    "calendar_name": "André",
    "email": "clive@email.co.uk",
    "participant_user_id": "8518c7ed-1df4-45e9-8dc4-d49b57ae0663",
    "event_body": "action=appointment.scheduled&id=399682887&calendarID=4038206&appointmentTypeID=14792299",
    "past_appointment_event_body": "action=appointment.scheduled&id=437321459&calendarID=4038206&appointmentTypeID=14792299",
    "event_body_with_user_metadata": "action=appointment.scheduled&id=503637409&calendarID=4038206&appointmentTypeID=14792299",
    "cancelled_appointment_id": 446315771,
    "interview_url": "https://meet.myinterview.com/1b879c51-2e29-46ae-bd36-3199860e65f2",
    "project_task_id": "273b420e-09cb-419c-8b57-b393595dba78",
}

appointments = {
    "appointment1": {  # hasn't received initial notification yet
        "appointment_id": "399682887",
        "appointment_type_id": "14792299",
        "acuity_info": {
            "id": 399682887,
            "firstName": "Clive",
            "lastName": "Cresswell",
            "phone": "",
            "email": "clive@email.co.uk",
            "date": "June 30, 2020",
            "time": "10:15",
            "endTime": "10:45",
            "dateCreated": "June 29, 2020",
            "datetimeCreated": "2020-06-29T16:45:48-0500",
            "datetime": "2020-06-30T10:15:00+0100",
            "price": "0.00",
            "priceSold": "0.00",
            "paid": "no",
            "amountPaid": "0.00",
            "type": "Test appointment",
            "appointmentTypeID": 14792299,
            "classID": None,
            "addonIDs": [],
            "category": "Tech development",
            "duration": "30",
            "calendar": "Andr\u00e9",
            "calendarID": 4038206,
            "certificate": None,
            "confirmationPage": "https://app.acuityscheduling.com/schedule.php?owner=19499339&action=appt&id%5B%5D=9d20ba8fc7801ff9bc599861c72937ca",
            "location": "",
            "notes": "DO NOT DELETE. Appointment used for automated testing.",
            "timezone": "Europe/London",
            "calendarTimezone": "Europe/London",
            "canceled": False,
            "canClientCancel": False,
            "canClientReschedule": False,
            "labels": None,
            "forms": [],
            "formsText": "Name: Clive Cresswell\nPhone: \nEmail: clive@email.co.uk\n",
            "isVerified": False,
            "scheduledBy": "andre@email.co.uk",
        },
        "calendar_id": "4038206",
        "calendar_name": "Andr\u00e9",
        "link": None,
        "participant_email": "clive@email.co.uk",
        "participant_user_id": None,
        "latest_participant_notification": "0000-00-00 00:00:00+00:00",
        "appointment_date": "2020-06-30",
        "appointment_type": {
            "type_id": "14792299",
            "name": "Test appointment",
            "category": "Tech development",
            "has_link": True,
            "send_notifications": True,
            "templates": None,
            "project_task_id": "273b420e-09cb-419c-8b57-b393595dba78",
            "details": None,
            "id": "14792299",
            "type": "acuity-appointment-type",
        },
        "type": "acuity-appointment",
    },
    "appointment2": {  # last notification received 3 days before appointment
        "appointment_id": "448161724",
        "appointment_type_id": "14649911",
        "acuity_info": {
            "id": 448161724,
            "firstName": "Altha",
            "lastName": "Alcorn",
            "phone": "",
            "email": "altha@email.co.uk",
            "date": "September 28, 2020",
            "time": "13:00",
            "endTime": "13:30",
            "dateCreated": "September 25, 2020",
            "datetimeCreated": "2020-09-25T05:48:18-0500",
            "datetime": "2020-09-28T13:00:00+0100",
            "price": "0.00",
            "priceSold": "0.00",
            "paid": "no",
            "amountPaid": "0.00",
            "type": "Development appointment",
            "appointmentTypeID": 14649911,
            "classID": None,
            "addonIDs": [],
            "category": "Tech development",
            "duration": "30",
            "calendar": "Andr\u00e9",
            "calendarID": 4038206,
            "certificate": None,
            "confirmationPage": "https://app.acuityscheduling.com/schedule.php?owner=19499339&action=appt&id%5B%5D=ab81fa72b0d0c1dead5057103c292bd3",
            "location": "",
            "notes": "",
            "timezone": "Europe/London",
            "calendarTimezone": "Europe/London",
            "canceled": False,
            "canClientCancel": False,
            "canClientReschedule": False,
            "labels": None,
            "forms": [],
            "formsText": "Name: Altha Alcorn\nPhone: \nEmail: altha@email.co.uk\n",
            "isVerified": False,
            "scheduledBy": "andre@email.co.uk",
        },
        "calendar_id": "4038206",
        "calendar_name": "Andr\u00e9",
        "link": None,
        "participant_email": "altha@email.co.uk",
        "participant_user_id": None,
        "latest_participant_notification": "2020-09-25 06:10:10+00:00",
        "appointment_date": "2020-09-28",
        "appointment_type": {
            "type_id": "14649911",
            "name": "Development appointment",
            "category": "Tech development",
            "has_link": None,
            "send_notifications": None,
            "templates": None,
            "project_task_id": "273b420e-09cb-419c-8b57-b393595dba78",
            "details": None,
            "id": "14649911",
            "type": "acuity-appointment-type",
        },
        "type": "acuity-appointment",
    },
    "appointment3": {  # last notification received 1 day before appointment
        "appointment_id": "451427483",
        "appointment_type_id": "17271544",
        "acuity_info": {
            "id": 451427483,
            "firstName": "Clive",
            "lastName": "Cresswell",
            "phone": "",
            "email": "clive@email.co.uk",
            "date": "October 2, 2020",
            "time": "13:15",
            "endTime": "14:00",
            "dateCreated": "October 1, 2020",
            "datetimeCreated": "2020-10-01T05:11:03-0500",
            "datetime": "2020-10-02T13:15:00+0100",
            "price": "0.00",
            "priceSold": "0.00",
            "paid": "no",
            "amountPaid": "0.00",
            "type": "Development appointment - no link",
            "appointmentTypeID": 17271544,
            "classID": None,
            "addonIDs": [],
            "category": "Tech development",
            "duration": "45",
            "calendar": "Andr\u00e9",
            "calendarID": 4038206,
            "certificate": None,
            "confirmationPage": "https://app.acuityscheduling.com/schedule.php?owner=19499339&action=appt&id%5B%5D=9edb5e9373f203a9398073e132eb0e7a",
            "location": "",
            "notes": "",
            "timezone": "Europe/London",
            "calendarTimezone": "Europe/London",
            "canceled": False,
            "canClientCancel": False,
            "canClientReschedule": False,
            "labels": None,
            "forms": [],
            "formsText": "Name: Clive Cresswell\nPhone: \nEmail: clive@email.co.uk\n",
            "isVerified": False,
            "scheduledBy": "andre@email.co.uk",
        },
        "calendar_id": "4038206",
        "calendar_name": "Andr\u00e9",
        "link": None,
        "participant_email": "clive@email.co.uk",
        "participant_user_id": None,
        "latest_participant_notification": "2020-10-01 05:13:40+00:00",
        "appointment_date": "2020-10-02",
        "appointment_type": {
            "type_id": "17271544",
            "name": "Development appointment - no link",
            "category": "Tech development",
            "has_link": False,
            "send_notifications": True,
            "templates": None,
            "project_task_id": "273b420e-09cb-419c-8b57-b393595dba78",
            "details": None,
            "id": "17271544",
            "type": "acuity-appointment-type",
        },
        "type": "acuity-appointment",
    },
    "appointment4": {  # hasn't received initial notification yet
        "appointment_id": "610938744",
        "appointment_type_id": "17271544",
        "acuity_info": {
            "addonIDs": [],
            "amountPaid": "0.00",
            "appointmentTypeID": 17271544,
            "calendar": "André",
            "calendarID": 4038206,
            "calendarTimezone": "Europe/London",
            "canClientCancel": True,
            "canClientReschedule": True,
            "canceled": False,
            "category": "_Tech development {{dev}}",
            "certificate": None,
            "classID": None,
            "confirmationPage": "REDACTED",
            "date": "October 1, 2023",
            "dateCreated": "June 10, 2021",
            "datetime": "2023-10-01T14:15:00+0100",
            "datetimeCreated": "2021-06-10T08:16:41-0500",
            "duration": "45",
            "email": "greg@email.co.uk",
            "endTime": "15:00",
            "firstName": "Greg",
            "forms": [
                {
                    "id": 1606751,
                    "name": "User metadata",
                    "values": [
                        {
                            "fieldID": 8861964,
                            "id": 1952068329,
                            "name": "anon_user_task_id",
                            "value": "",
                        },
                        {
                            "fieldID": 8941105,
                            "id": 1952068330,
                            "name": "anon_project_specific_user_id",
                            "value": "",
                        },
                    ],
                }
            ],
            "formsText": "Name: Greg Gregory\n"
            "Phone: 01234567890\n"
            "Email: greg@email.co.uk\n"
            "\n"
            "User metadata\n"
            "============\n"
            "anon_user_task_id: \n"
            "\n"
            "anon_project_specific_user_id: \n"
            "\n",
            "id": 610938744,
            "isVerified": False,
            "labels": None,
            "lastName": "Gregory",
            "location": "",
            "notes": "",
            "paid": "no",
            "phone": "01234567890",
            "price": "0.00",
            "priceSold": "0.00",
            "scheduledBy": "REDACTED",
            "time": "14:15",
            "timezone": "Asia/Bangkok",
            "type": "Development appointment - no link",
        },
        "calendar_id": "4038206",
        "calendar_name": "Andr\u00e9",
        "link": None,
        "participant_email": "greg@email.co.uk",
        "participant_user_id": None,
        "latest_participant_notification": "0000-00-00 00:00:00+00:00",
        "appointment_date": "2023-10-01",
        "appointment_type": {
            "type_id": "17271544",
            "name": "Development appointment - no link",
            "category": "Tech development",
            "has_link": False,
            "send_notifications": True,
            "templates": None,
            "project_task_id": "273b420e-09cb-419c-8b57-b393595dba78",
            "details": None,
            "id": "17271544",
            "type": "acuity-appointment-type",
        },
        "type": "acuity-appointment",
    },
    "appointment5": {  # hasn't received initial notification yet
        "appointment_id": "451904182",
        "appointment_type_id": "17271544",
        "acuity_info": {
            "id": 451904182,
            "firstName": "Eddie",
            "lastName": "Eagleton",
            "phone": "",
            "email": "eddie@email.co.uk",
            "date": "October 15, 2020",
            "time": "11:00",
            "endTime": "11:45",
            "dateCreated": "October 2, 2020",
            "datetimeCreated": "2020-10-01T19:26:20-0500",
            "datetime": "2020-10-15T11:00:00+0100",
            "price": "0.00",
            "priceSold": "0.00",
            "paid": "no",
            "amountPaid": "0.00",
            "type": "Development appointment - no link",
            "appointmentTypeID": 17271544,
            "classID": None,
            "addonIDs": [],
            "category": "Tech development",
            "duration": "45",
            "calendar": "Andr\u00e9",
            "calendarID": 4038206,
            "certificate": None,
            "confirmationPage": "https://app.acuityscheduling.com/schedule.php?owner=19499339&action=appt&id%5B%5D=3b7422961f0ef184e484a94e04e237c9",
            "location": "",
            "notes": "",
            "timezone": "Europe/London",
            "calendarTimezone": "Europe/London",
            "canceled": False,
            "canClientCancel": True,
            "canClientReschedule": True,
            "labels": None,
            "forms": [],
            "formsText": "Name: Eddie Eagleton\nPhone: \nEmail: eddie@email.co.uk\n",
            "isVerified": False,
            "scheduledBy": "andre@email.co.uk",
        },
        "calendar_id": "4038206",
        "calendar_name": "Andr\u00e9",
        "link": None,
        "participant_email": "eddie@email.co.uk",
        "participant_user_id": None,
        "latest_participant_notification": "0000-00-00 00:00:00+00:00",
        "appointment_date": "2020-10-15",
        "appointment_type": {
            "type_id": "17271544",
            "name": "Development appointment - no link",
            "category": "Tech development",
            "has_link": False,
            "send_notifications": True,
            "templates": None,
            "project_task_id": "273b420e-09cb-419c-8b57-b393595dba78",
            "details": None,
            "id": "17271544",
            "type": "acuity-appointment-type",
        },
        "type": "acuity-appointment",
    },
    "appointment6": {  # hasn't received initial notification yet
        "appointment_id": "448161419",
        "appointment_type_id": "17268193",
        "acuity_info": {
            "id": 448161419,
            "firstName": "Altha",
            "lastName": "Alcorn",
            "phone": "",
            "email": "altha@email.co.uk",
            "date": "September 28, 2020",
            "time": "10:30",
            "endTime": "11:30",
            "dateCreated": "September 25, 2020",
            "datetimeCreated": "2020-09-25T05:46:24-0500",
            "datetime": "2020-09-28T10:30:00+0100",
            "price": "0.00",
            "priceSold": "0.00",
            "paid": "no",
            "amountPaid": "0.00",
            "type": "Test appointment - no notifications",
            "appointmentTypeID": 17268193,
            "classID": None,
            "addonIDs": [],
            "category": "Tech development",
            "duration": "60",
            "calendar": "Andr\u00e9",
            "calendarID": 4038206,
            "certificate": None,
            "confirmationPage": "https://app.acuityscheduling.com/schedule.php?owner=19499339&action=appt&id%5B%5D=2013bc86dd386187bc2475eaab50dab3",
            "location": "",
            "notes": "",
            "timezone": "Europe/London",
            "calendarTimezone": "Europe/London",
            "canceled": False,
            "canClientCancel": False,
            "canClientReschedule": False,
            "labels": None,
            "forms": [],
            "formsText": "Name: Altha Alcorn\nPhone: \nEmail: altha@email.co.uk\n",
            "isVerified": False,
            "scheduledBy": "andre@email.co.uk",
        },
        "calendar_id": "4038206",
        "calendar_name": "Andr\u00e9",
        "link": None,
        "participant_email": "altha@email.co.uk",
        "participant_user_id": None,
        "latest_participant_notification": "0000-00-00 00:00:00+00:00",
        "appointment_date": "2020-09-28",
        "appointment_type": {
            "type_id": "17268193",
            "name": "Test appointment - no notifications",
            "category": "Tech development",
            "has_link": True,
            "send_notifications": False,
            "templates": None,
            "project_task_id": "273b420e-09cb-419c-8b57-b393595dba78",
            "details": None,
            "id": "17268193",
            "type": "acuity-appointment-type",
        },
        "type": "acuity-appointment",
    },
    "views1": {
        "acuity_info": {
            "id": 647075227,
            "firstName": "Eddie",
            "lastName": "Eagleton",
            "phone": "",
            "email": "eddie@email.co.uk",
            "date": "August 9, 2026",
            "time": "10:15",
            "endTime": "10:45",
            "dateCreated": "August 9, 2021",
            "datetimeCreated": "2021-08-09T08:46:48-0500",
            "datetime": "2026-08-09T10:15:00+0100",
            "price": "0.00",
            "priceSold": "0.00",
            "paid": "no",
            "amountPaid": "0.00",
            "type": "Test appointment",
            "appointmentTypeID": 14792299,
            "classID": None,
            "addonIDs": [],
            "category": "_Tech development {{dev}}",
            "duration": "30",
            "calendar": "André",
            "calendarID": 4038206,
            "certificate": None,
            "confirmationPage": "REDACTED",
            "location": "",
            "notes": "",
            "timezone": "Europe/London",
            "calendarTimezone": "Europe/London",
            "canceled": False,
            "canClientCancel": True,
            "canClientReschedule": True,
            "labels": None,
            "forms": [
                {
                    "id": 1606751,
                    "name": "User metadata",
                    "values": [
                        {
                            "id": 2096884983,
                            "fieldID": 8861964,
                            "value": "4a7a29e8-2869-469f-a922-5e9ff5af4583",
                            "name": "anon_user_task_id",
                        },
                        {
                            "id": 2096884984,
                            "fieldID": 8941105,
                            "value": "a7a8e630-cb7e-4421-a9b2-b8bad0298267",
                            "name": "anon_project_specific_user_id",
                        },
                    ],
                }
            ],
            "formsText": "Name: Eddie Eagleton\nPhone: \nEmail: eddie@email.co.uk\n\n"
            "User metadata\n============\nanon_user_task_id: "
            "4a7a29e8-2869-469f-a922-5e9ff5af4583\n\nanon_project_specific_user_id: "
            "a7a8e630-cb7e-4421-a9b2-b8bad0298267\n\n",
            "isVerified": False,
            "scheduledBy": "REDACTED",
        },
        "add_to_calendar_links": None,
        "anon_project_specific_user_id": "a7a8e630-cb7e-4421-a9b2-b8bad0298267",
        "anon_user_task_id": "4a7a29e8-2869-469f-a922-5e9ff5af4583",
        "appointment_date": "2026-08-09",
        "appointment_datetime": "2026-08-09T10:15:00+0100",
        "appointment_duration": "30",
        "appointment_id": "647075227",
        "appointment_timezone": "Europe/London",
        "appointment_type": {
            "category": "_Tech development {{dev}}",
            "details": None,
            "has_link": True,
            "id": "14792299",
            "name": "Test appointment",
            "project_task_id": "273b420e-09cb-419c-8b57-b393595dba78",
            "send_notifications": True,
            "system": None,
            "templates": None,
            "type": "acuity-appointment-type",
            "type_id": 14792299,
        },
        "appointment_type_id": "14792299",
        "calendar_id": "4038206",
        "calendar_name": "André",
        "calendar_timezone": "Europe/London",
        "created": "2021-08-09 10:30:33.324722+00:00",
        "details": None,
        "id": "647075227",
        "interview_id": "88c1c1cc-3f17-4ece-b4b9-8ea955e7db6f",
        "interview_room_url": "https://video.thiscovery.org/live/2eb7d0a8-d30a-4e71-bf37-d29a17088f45",
        "interviewer_emails": "interviewer_1@email.com, interviewer_2@email.com, "
        "interviewer_3@email.com",
        "latest_participant_notification": "2021-08-09 10:30:34.739689+00:00",
        "modified": "2021-08-09 10:30:34.741723+00:00",
        "participant_email": None,
        "participant_user_id": None,
        "project_task_id": "a4f8ff7c-decf-475b-9356-24e91d4e025f",
        "room_phone_number": "+44123456789",
        "room_phone_pin": "12345678",
        "type": "views-appointment",
    },
    "views2": {  # cancelled appointment
        "acuity_info": {
            "addonIDs": [],
            "amountPaid": "0.00",
            "appointmentTypeID": 14792299,
            "calendar": "André",
            "calendarID": 4038206,
            "calendarTimezone": "Europe/London",
            "canClientCancel": False,
            "canClientReschedule": False,
            "canceled": True,
            "category": "_Tech development {{dev}}",
            "certificate": None,
            "classID": None,
            "confirmationPage": "REDACTED",
            "date": "August 27, 2026",
            "dateCreated": "August 27, 2021",
            "datetime": "2026-08-27T10:15:00+0100",
            "datetimeCreated": "2021-08-27T08:31:28-0500",
            "duration": "30",
            "email": "eddie@email.co.uk",
            "endTime": "10:45",
            "firstName": "Eddie",
            "forms": [
                {
                    "id": 1606751,
                    "name": "User metadata",
                    "values": [
                        {
                            "fieldID": 8861964,
                            "id": 2158346857,
                            "name": "anon_user_task_id",
                            "value": "4a7a29e8-2869-469f-a922-5e9ff5af4583",
                        },
                        {
                            "fieldID": 8941105,
                            "id": 2158346858,
                            "name": "anon_project_specific_user_id",
                            "value": "a7a8e630-cb7e-4421-a9b2-b8bad0298267",
                        },
                    ],
                }
            ],
            "formsText": "Name: Eddie Eagleton\n"
            "Phone: \n"
            "Email: eddie@email.co.uk\n"
            "\n"
            "User metadata\n"
            "============\n"
            "anon_user_task_id: 4a7a29e8-2869-469f-a922-5e9ff5af4583\n"
            "\n"
            "anon_project_specific_user_id: "
            "a7a8e630-cb7e-4421-a9b2-b8bad0298267\n"
            "\n",
            "id": 658731287,
            "isVerified": False,
            "labels": None,
            "lastName": "Eagleton",
            "location": "",
            "noShow": False,
            "notes": "",
            "paid": "no",
            "phone": "",
            "price": "0.00",
            "priceSold": "0.00",
            "scheduledBy": "REDACTED",
            "time": "10:15",
            "timezone": "Europe/London",
            "type": "Test appointment",
        },
        "add_to_calendar_links": None,
        "anon_project_specific_user_id": "a7a8e630-cb7e-4421-a9b2-b8bad0298267",
        "anon_user_task_id": "4a7a29e8-2869-469f-a922-5e9ff5af4583",
        "appointment_date": "2026-08-27",
        "appointment_datetime": "2026-08-27T10:15:00+0100",
        "appointment_duration": "30",
        "appointment_id": "658731287",
        "appointment_timezone": "Europe/London",
        "appointment_type": {
            "category": "_Tech development {{dev}}",
            "details": None,
            "has_link": True,
            "id": "14792299",
            "name": "Test appointment",
            "project_task_id": "273b420e-09cb-419c-8b57-b393595dba78",
            "send_notifications": True,
            "system": None,
            "templates": None,
            "type": "acuity-appointment-type",
            "type_id": 14792299,
        },
        "appointment_type_id": "14792299",
        "calendar_id": "4038206",
        "calendar_name": "André",
        "calendar_timezone": "Europe/London",
        "created": "2021-08-09 10:30:33.324722+00:00",
        "details": None,
        "id": "658731287",
        "interview_id": "5bae6605-7cba-4603-ae93-1ac4fc7b2eba",
        "interview_room_url": "https://video.thiscovery.org/live/943d43fd-76ae-4083-929c-948a1ce6d918",
        "interviewer_emails": "interviewer_1@email.com, interviewer_2@email.com",
        "latest_participant_notification": "2021-08-19 10:30:34.739689+00:00",
        "modified": "2021-08-19 10:30:34.741723+00:00",
        "participant_email": None,
        "participant_user_id": None,
        "project_task_id": "a4f8ff7c-decf-475b-9356-24e91d4e025f",
        "room_phone_number": "+44123456789",
        "room_phone_pin": "12345678",
        "type": "views-appointment",
    },
    "views3": {
        "acuity_info": {
            "id": 660129794,
            "firstName": "Eddie",
            "lastName": "Eagleton",
            "phone": "",
            "email": "eddie@email.co.uk",
            "date": "August 30, 2025",
            "time": "10:15",
            "endTime": "10:45",
            "dateCreated": "August 30, 2021",
            "datetimeCreated": "2021-08-30T05:40:10-0500",
            "datetime": "2025-08-30T10:15:00+0100",
            "price": "0.00",
            "priceSold": "0.00",
            "paid": "no",
            "amountPaid": "0.00",
            "type": "Development appointment",
            "appointmentTypeID": 14649911,
            "classID": None,
            "addonIDs": [],
            "category": "_Tech development {{dev}}",
            "duration": "30",
            "calendar": "André",
            "calendarID": 4038206,
            "certificate": None,
            "confirmationPage": "REDACTED",
            "location": "",
            "notes": "",
            "timezone": "Europe/London",
            "calendarTimezone": "Europe/London",
            "canceled": False,
            "canClientCancel": True,
            "canClientReschedule": True,
            "labels": None,
            "forms": [
                {
                    "id": 1606751,
                    "name": "User metadata",
                    "values": [
                        {
                            "id": 2166234565,
                            "fieldID": 8861964,
                            "value": "2035dce9-9745-46cc-8db0-3e8de47c463b",
                            "name": "anon_user_task_id",
                        },
                        {
                            "id": 2166234566,
                            "fieldID": 8941105,
                            "value": "7e6e4bca-4f0b-4f71-8660-790c1baf3b11",
                            "name": "anon_project_specific_user_id",
                        },
                    ],
                }
            ],
            "formsText": "Name: Eddie Eagleton\nPhone: \nEmail: eddie@email.co.uk\n\n"
            "User metadata\n============\nanon_user_task_id: 2035dce9-9745-46cc-8db0-3e8de47c463b\n\n"
            "anon_project_specific_user_id: 7e6e4bca-4f0b-4f71-8660-790c1baf3b11\n\n",
            "isVerified": False,
            "scheduledBy": "REDACTED",
        },
        "add_to_calendar_links": None,
        "anon_project_specific_user_id": "7e6e4bca-4f0b-4f71-8660-790c1baf3b11",
        "anon_user_task_id": "2035dce9-9745-46cc-8db0-3e8de47c463b",
        "appointment_date": "2026-08-30",
        "appointment_datetime": "2025-08-30T10:15:00+0100",
        "appointment_duration": "30",
        "appointment_id": "660129794",
        "appointment_timezone": "Europe/London",
        "appointment_type": {
            "category": "_Tech development {{dev}}",
            "details": None,
            "has_link": False,
            "id": "14649911",
            "name": "Development appointment",
            "project_task_id": "a4f8ff7c-decf-475b-9356-24e91d4e025f",
            "send_notifications": False,
            "system": None,
            "templates": None,
            "type": "acuity-appointment-type",
            "type_id": 14792299,
        },
        "appointment_type_id": "14649911",
        "calendar_id": "4038206",
        "calendar_name": "André",
        "calendar_timezone": "Europe/London",
        "created": "2021-08-09 10:30:33.324722+00:00",
        "details": None,
        "id": "660129794",
        "interview_id": "5bae6605-7cba-4603-ae93-1ac4fc7b2eba",
        "interview_room_url": "https://video.thiscovery.org/live/b7b519ec-de04-41a5-b386-bd336c8af1f7",
        "interviewer_emails": "interviewer_1@email.com, interviewer_2@email.com",
        "latest_participant_notification": "2021-08-19 10:30:34.739689+00:00",
        "modified": "2021-08-19 10:30:34.741723+00:00",
        "participant_email": None,
        "participant_user_id": None,
        "project_task_id": "a4f8ff7c-decf-475b-9356-24e91d4e025f",
        "room_phone_number": "+44123456789",
        "room_phone_pin": "12345678",
        "type": "views-appointment",
    },
}
custom_properties = [
    {"name": "user_first_name", "required": True},
    {"name": "project_name", "required": True},
    {"name": "interviewer_first_name", "required": False},
    {"name": "appointment_date", "required": False},
    {"name": "appointment_time", "required": False},
    {"name": "appointment_timezone", "required": False},
    {"name": "appointment_url", "required": False},
    {"name": "appointment_telephone", "required": False},
    {"name": "appointment_duration", "required": False},
    {"name": "interview_url", "required": True},
    {"name": "appointment_reschedule_url", "required": True},
]

base_template = {
    "bcc": ["thiscovery_dev@email.com"],
    "cc": [],
    "contact_properties": [],
}

templates = {
    "interview_booked_web_participant": {
        **base_template,
        "name": "interview_booked_web_participant",
        "custom_properties": [
            {"name": "project_short_name", "required": True},
            {"name": "user_first_name", "required": True},
            {"name": "appointment_date", "required": True},
            {"name": "appointment_duration", "required": True},
            {"name": "appointment_reschedule_url", "required": True},
            {"name": "interview_url", "required": True},
            {"name": "appointment_time", "required": False},
            {"name": "interviewer_first_name", "required": False},
        ],
    },
    "interview_booked_researcher": {
        **base_template,
        "name": "interview_booked_researcher",
        "custom_properties": [
            {"name": "project_short_name", "required": True},
            {"name": "appointment_date", "required": True},
            {"name": "appointment_duration", "required": True},
            {"name": "interviewer_url", "required": True},
            {"name": "user_first_name", "required": False},
            {"name": "user_last_name", "required": False},
            {"name": "user_email", "required": False},
            {"name": "anon_project_specific_user_id", "required": False},
            {"name": "interviewer_first_name", "required": False},
            {"name": "appointment_type_name", "required": False},
            {"name": "appointment_time", "required": False},
        ],
        "hs_template_id": "35536146856",
    },
    "interview_reminder_web_participant": {
        "name": "interview_reminder_web_participant",
        **base_template,
        "custom_properties": [
            {"name": "user_first_name", "required": False},
            {"name": "interviewer_first_name", "required": False},
            {"name": "project_short_name", "required": False},
            {"name": "appointment_date", "required": True},
            {"name": "appointment_time", "required": True},
            {"name": "appointment_duration", "required": True},
            {"name": "interview_url", "required": True},
            {"name": "appointment_reschedule_url", "required": True},
        ],
        "details": {
            "preview_url": "https://preview.hs-sites.com/_hcms/preview/content/35541003495?portalId=4783957&_preview=true&cacheBust=0&preview_key=DaZTXHRr&from_buffer=false"
        },
        "from": os.environ["TESTER_EMAIL"],
        "hs_template_id": "35541003495",
        "modified": "2020-10-08 13:50:38.189514+01:00",
        "type": "interviewee-reminder",
    },
    "interview_cancelled_participant": {
        "name": "interview_cancelled_participant",
        **base_template,
        "custom_properties": [
            {"name": "project_short_name", "required": True},
            {"name": "user_first_name", "required": True},
        ],
        "details": {
            "preview_url": "https://preview.hs-sites.com/_hcms/preview/content/35439874586?portalId=4783957&_preview=true&cacheBust=1601460888949&preview_key=kbBoCxaO&from_buffer=false"
        },
        "from": os.environ["TESTER_EMAIL"],
        "hs_template_id": "35439874586",
    },
    "interview_cancelled_researcher": {
        "name": "interview_cancelled_researcher",
        **base_template,
        "custom_properties": [
            {"name": "appointment_date", "required": True},
            {"name": "appointment_duration", "required": True},
            {"name": "interviewer_url", "required": True},
            {"name": "user_first_name", "required": False},
            {"name": "user_last_name", "required": False},
            {"name": "user_email", "required": False},
            {"name": "anon_project_specific_user_id", "required": False},
            {"name": "interviewer_first_name", "required": False},
            {"name": "appointment_type_name", "required": False},
            {"name": "appointment_time", "required": False},
        ],
        "from": os.environ["TESTER_EMAIL"],
        "hs_template_id": "35541640233",
    },
    "interview_rescheduled_web_participant": {
        "name": "interview_rescheduled_web_participant",
        **base_template,
        "custom_properties": [
            {"name": "project_short_name", "required": True},
            {"name": "user_first_name", "required": True},
            {"name": "appointment_date", "required": True},
            {"name": "appointment_duration", "required": True},
            {"name": "appointment_reschedule_url", "required": True},
            {"name": "interview_url", "required": True},
            {"name": "appointment_time", "required": False},
            {"name": "interviewer_first_name", "required": False},
        ],
    },
    "interview_rescheduled_researcher": {
        "name": "interview_rescheduled_researcher",
        **base_template,
        "custom_properties": [
            {"name": "project_short_name", "required": True},
            {"name": "appointment_date", "required": True},
            {"name": "appointment_duration", "required": True},
            {"name": "interviewer_url", "required": True},
            {"name": "user_first_name", "required": False},
            {"name": "user_last_name", "required": False},
            {"name": "user_email", "required": False},
            {"name": "anon_project_specific_user_id", "required": False},
            {"name": "interviewer_first_name", "required": False},
            {"name": "appointment_type_name", "required": False},
            {"name": "appointment_time", "required": False},
        ],
    },
    "views_interview_booked_participant": {
        "name": "views_interview_booked_participant",
        **base_template,
        "custom_properties": [
            {"name": "user_first_name", "required": True},
            {"name": "project_name", "required": True},
            {"name": "interviewer_first_name", "required": False},
            {"name": "appointment_date", "required": False},
            {"name": "appointment_time", "required": False},
            {"name": "appointment_timezone", "required": False},
            {"name": "appointment_url", "required": False},
            {"name": "appointment_telephone", "required": False},
            {"name": "appointment_duration", "required": False},
        ],
        "from": os.environ["TESTER_EMAIL"],
        "hs_template_id": "48978716962",
    },
    "views_interview_cancelled_researcher": {
        "name": "views_interview_cancelled_researcher",
        **base_template,
        "custom_properties": [
            {"name": "user_first_name", "required": True},
            {"name": "user_email", "required": True},
            {"name": "project_name", "required": True},
            {"name": "appointment_date", "required": False},
            {"name": "appointment_time", "required": False},
            {"name": "appointment_timezone", "required": False},
        ],
        "from": os.environ["TESTER_EMAIL"],
        "hs_template_id": "49153438576",
    },
    "views_interview_cancelled_participant": {
        "name": "views_interview_cancelled_participant",
        **base_template,
        "custom_properties": [
            {"name": "user_first_name", "required": True},
            {"name": "project_name", "required": True},
            {"name": "appointment_url", "required": True},
        ],
        "hs_template_id": "49040074146",
        "from": os.environ["TESTER_EMAIL"],
    },
    "views_interview_booked_researcher": {
        **base_template,
        "name": "views_interview_booked_researcher",
        "custom_properties": [
            {"name": "project_name", "required": True},
            {"name": "user_email", "required": True},
            {"name": "user_first_name", "required": True},
            {"name": "anon_project_specific_user_id", "required": False},
            {"name": "appointment_date", "required": False},
            {"name": "appointment_time", "required": False},
            {"name": "appointment_timezone", "required": False},
            {"name": "appointment_duration", "required": False},
            {"name": "appointment_telephone", "required": False},
            {"name": "appointment_url", "required": False},
        ],
        "from": os.environ["TESTER_EMAIL"],
        "hs_template_id": "49150622560",
    },
    "views_interview_reminder_participant": {
        "id": 123,
        **base_template,
        "name": "views_interview_reminder_participant",
        "contact_properties": [],
        "details": {
            "preview_url": "https://4783957.hubspotpreview-na1.com/_hcms/preview/content/49042986330?portalId=4783957&_preview=true&cacheBust=0&preview_key=TokjNiqJ&from_buffer=false"
        },
        "from": os.environ["TESTER_EMAIL"],
        "hs_template_id": "49042986330",
        "modified": "2021-06-20 22:02:08.139317+01:00",
        "type": "views-email-template",
        "custom_properties": [
            {"name": "user_first_name", "required": True},
            {"name": "appointment_duration", "required": False},
            {"name": "project_task_id", "required": False},
            {"name": "appointment_time", "required": False},
            {"name": "appointment_timezone", "required": False},
            {"name": "interviewer_first_name", "required": False},
            {"name": "appointment_url", "required": False},
            {"name": "appointment_telephone", "required": False},
        ],
    },
    "views_interview_rescheduled_participant": {
        "name": "views_interview_rescheduled_participant",
        **base_template,
        "custom_properties": [
            {"name": "user_first_name", "required": True},
            {"name": "project_name", "required": True},
            {"name": "interviewer_first_name", "required": True},
            {"name": "appointment_date", "required": True},
            {"name": "appointment_duration", "required": True},
            {"name": "appointment_time", "required": True},
            {"name": "appointment_timezone", "required": True},
            {"name": "appointment_url", "required": True},
            {"name": "appointment_telephone", "required": False},
        ],
        "hs_template_id": "48980164688",
    },
    "views_interview_rescheduled_researcher": {
        "name": "views_interview_rescheduled_researcher",
        **base_template,
        "custom_properties": [
            {"name": "user_first_name", "required": True},
            {"name": "user_email", "required": True},
            {"name": "anon_project_specific_user_id", "required": False},
            {"name": "project_name", "required": True},
            {"name": "appointment_date", "required": False},
            {"name": "appointment_time", "required": False},
            {"name": "appointment_timezone", "required": False},
            {"name": "appointment_duration", "required": False},
            {"name": "appointment_telephone", "required": False},
            {"name": "appointment_url", "required": False},
        ],
        "hs_template_id": "49155844194",
    },
    # "unittests_email_template_1": {
    #     "id": "unittests_email_template_1",
    #     "bcc": ["thiscovery_dev@email.com"],
    #     "cc": ["this_researcher@email.com"],
    #     "contact_properties": [],
    #     "custom_properties": [
    #         {"name": "project_task_name", "required": True},
    #         {"name": "project_task_description", "required": True},
    #         {"name": "project_results_url", "required": False}
    #     ],
    #     "from": "Sender Name <sender@hubspot.com>",
    #     "hs_template_id": "33531457008",
    # }
}

# region Acuity router events
acuity_router_event_template = {
    "version": "0",
    "id": "3cc7968d-6e99-04d1-1c1b-fab805370baa",
    "detail-type": "processed_acuity_event",
    "source": "acuity",
    "account": "REDACTED",
    "time": "2021-06-09T09:33:40Z",
    "region": "REDACTED",
    "resources": [],
    "detail": {
        "body": "action=appointment.{event_type}&id={appointment_id}&calendarID={calendar_id}&appointmentTypeID={appointment_type_id}",
        "target_account": "REDACTED",
        "target_environment": "dev",
    },
}
# endregion


def eb_event_detail_from_acuity_info(acuity_info_dict):
    anon_user_task_id = None
    anon_psu_id = None
    user_metadata_values = acuity_info_dict["forms"][0]["values"]
    for a in user_metadata_values:
        name = a["name"]
        value = a["value"]
        if name == "anon_user_task_id":
            anon_user_task_id = value
        elif name == "anon_project_specific_user_id":
            anon_psu_id = value

    return {
        "anon_project_specific_user_id": anon_psu_id,
        "anon_user_task_id": anon_user_task_id,
        "appointment_datetime": acuity_info_dict["datetime"],
        "appointment_duration": acuity_info_dict["duration"],
        "appointment_id": str(acuity_info_dict["id"]),
        "appointment_timezone": acuity_info_dict["timezone"],
        "appointment_type": acuity_info_dict["type"],
        "appointment_type_id": str(acuity_info_dict["appointmentTypeID"]),
        "calendar_id": str(acuity_info_dict["calendarID"]),
        "calendar_name": acuity_info_dict["calendar"],
        "calendar_timezone": acuity_info_dict["calendarTimezone"],
        "interview_id": "2132ba81-92c2-4793-ad59-59039833c608",  # arbitrary uuid
        "interview_room_url": td["interview_url"],
        "project_task_id": td["project_task_id"],
        "room_phone_number": "+44 (0)1111 111 111",
        "room_phone_pin": "11111111",
    }


# region interview system
TEST_INTERVIEW_BOOKED_EB_EVENT = {
    "version": "0",
    "id": "63b9a0a8-389a-4131-bd11-d8fc2d3db845",
    "detail-type": "interview_booked",
    "detail": {
        "anon_project_specific_user_id": TEST_USER_INTERVIEW_TASK[
            "anon_project_specific_user_id"
        ],
        "anon_user_task_id": TEST_USER_INTERVIEW_TASK["anon_user_task_id"],
        "appointment_datetime": "2025-06-30T10:15:00+0100",
        "appointment_duration": "45",
        "appointment_id": td["test_appointment_id"],
        "appointment_timezone": "Europe/London",
        "appointment_type": "Test appointment",
        "appointment_type_id": td["test_appointment_type_id"],
        "calendar_id": td["calendar_id"],
        "calendar_name": td["calendar_name"],
        "calendar_timezone": "Europe/London",
        "interview_id": "88c1c1cc-3f17-4ece-b4b9-8ea955e7db6f",
        "interview_room_url": td["interview_url"],
        "project_task_id": td["project_task_id"],
        "room_phone_number": "+44 (0)1111 111 111",
        "room_phone_pin": "11111111",
    },
    "source": "thiscovery_video",
    "account": "REDACTED",
    "region": "REDACTED",
    "resources": [],
    "time": "2021-02-12T10:57:09Z",
}

TEST_INTERVIEW_RESCHEDULED_EB_EVENT = {
    "version": "0",
    "id": "092f8328-27b2-4e6c-9620-24cb8a3eb24f",
    "detail-type": "interview_rescheduled",
    "detail": {
        "anon_project_specific_user_id": TEST_USER_INTERVIEW_TASK[
            "anon_project_specific_user_id"
        ],
        "anon_user_task_id": TEST_USER_INTERVIEW_TASK["anon_user_task_id"],
        "appointment_datetime": "2025-06-30T10:15:00+0100",  # "2025-11-08T18:15:00+0000"
        "appointment_duration": "45",
        "appointment_id": td["test_appointment_id"],
        "appointment_timezone": "Europe/London",
        "appointment_type": "Test appointment",
        "appointment_type_id": td["test_appointment_type_id"],
        "calendar_id": td["calendar_id"],
        "calendar_name": td["calendar_name"],
        "calendar_timezone": "Europe/London",
        "interview_id": "c954f49f-3b1a-41d3-b36a-64b8fec19468",
        "interview_room_url": td["interview_url"],
        "project_task_id": td["project_task_id"],
        "room_phone_number": "+44 (0)1111 111 111",
        "room_phone_pin": "11111111",
    },
    "source": "thiscovery_video",
    "account": "REDACTED",
    "region": "REDACTED",
    "resources": [],
    "time": "2021-02-12T10:57:09Z",
}

TEST_INTERVIEW_CANCELLED_EB_EVENT = {
    "version": "0",
    "id": "092f8328-27b2-4e6c-9620-24cb8a3eb24f",
    "detail-type": "interview_cancelled",
    "detail": {
        "anon_project_specific_user_id": TEST_USER_INTERVIEW_TASK[
            "anon_project_specific_user_id"
        ],
        "anon_user_task_id": TEST_USER_INTERVIEW_TASK["anon_user_task_id"],
        "appointment_datetime": "2025-06-30T10:15:00+0100",
        "appointment_duration": "45",
        "appointment_id": td["test_appointment_id"],
        "appointment_timezone": "Europe/London",
        "appointment_type": "Test appointment",
        "appointment_type_id": td["test_appointment_type_id"],
        "calendar_id": td["calendar_id"],
        "calendar_name": td["calendar_name"],
        "calendar_timezone": "Europe/London",
        "interview_id": "c954f49f-3b1a-41d3-b36a-64b8fec19468",
        "interview_room_url": td["interview_url"],
        "project_task_id": td["project_task_id"],
    },
    "source": "thiscovery_video",
    "account": "REDACTED",
    "region": "REDACTED",
    "resources": [],
    "time": "2021-02-12T10:57:09Z",
}

test_calendar = {
    "block_monday_morning": False,
    "description": "",
    "email": os.environ["TEST_CALENDAR_EMAIL"],
    "emails_to_notify": [
        "fred@email.co.uk",
        "wilma@email.co.uk",
    ],
    "id": 4038206,
    "image": False,
    "label": "André",
    "location": "",
    "myinterview_link": "https://meet.myinterview.com/5f64ccbd-b2e3-44e9-aed2-53c55cca4ef5",
    "name": "André",
    "thumbnail": False,
    "timezone": "Europe/London",
    "type": "acuity-calendar",
}

test_calendar_b = {
    "block_monday_morning": True,
    "description": "",
    "email": os.environ["TEST_CALENDAR_EMAIL"],
    "emails_to_notify": [
        "betty@email.co.uk",
        "barney@email.co.uk",
    ],
    "id": 4038207,
    "image": False,
    "label": "Andy",
    "location": "",
    "myinterview_link": "https://meet.myinterview.com/5f64ccbd-b2e3-44e9-aed2-53c55cca4ef5",
    "name": "Andy",
    "thumbnail": False,
    "timezone": "Europe/London",
    "type": "acuity-calendar",
}

test_block = {
    "calendarID": 4038206,
    "calendarTimezone": "Europe/London",
    "description": "Wednesday, December 25, 2030 09:00 - 17:00",
    "end": "2030-12-25T17:00:00+0000",
    "managed": False,
    "notes": "Xmas break",
    "recurring": None,
    "serviceGroupID": 4038206,
    "start": "2030-12-25T09:00:00+0000",
    "until": None,
}
# endregion
