name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  PIPELINE_USER_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_NAMED_REPO }}
  PIPELINE_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_NAMED_REPO }}
  AWS_REGION: eu-west-1
  STACK_NAME: thiscovery-lib-acuity


jobs:
  load-secrets:
    name: Deploy to test env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure testing environment
        uses: THIS-Labs/actions-configure-test-env@v0.16
        with:
          afs25_account: ${{ secrets.AFS25_AWS_ACCOUNT }}
          sem86_account: ${{ secrets.SEM86_AWS_ACCOUNT }}
          amp205_account: ${{ secrets.AMP205_AWS_ACCOUNT }}